### ISSUE TITLE
Does not work with names or paths with spaces.

### ISSUE THREAD

**Issue by cesar-0n** [nils-soderman/vscode-batch-runner#1]
For example:
`D:\Desktop\bat's\TEST AREA\file.bat`
results in:
`"D:/Desktop/bat's/TEST" is not recognized as an internal or external command, program, or executable batch file.`
but if you type in the console between quotes
`"D:\Desktop\bat's\TEST AREA\file.bat"`
it works

**Comment by nils-soderman** [comment]
Thanks for letting me know! :)
This should now be fixed in v0.0.2 ([#0a6b54a](https://github.com/nils-soderman/vscode-batch-runner/commit/0a6b54acd3938aa4490c9b68c79e5b3eee8a8ff8))

Cheers,
Nils
