### ISSUE TITLE
Run batches in the new Terminal

### ISSUE THREAD

**Issue by nidnesandne** [nils-soderman/vscode-batch-runner#11]
I use this extension to test batch files.
When I run various batch files, they run in the same terminal, so I have trouble with the previous environment variables being remained.

So, we would like to have an option to run the batch file in a new terminal. For example, "Run Batch File in new Terminal" menu or configuring default behavior in the Settings.

**Comment by nils-soderman** [comment]
Hi,

That's a good point I hadn't thought about, and I feel like we should probably always reset the terminal between each run.
Will look into it!

**Comment by nils-soderman** [comment]
With the latest release (1.1.1), the terminal is now restarted between each run.
