### ISSUE TITLE
Save before run

### ISSUE THREAD

**Issue by brokeDude2901** [nils-soderman/vscode-batch-runner#14]
Ability to save before run bat file

**Comment by nils-soderman** [comment]
I like the idea, will look into adding it for the next update!

**Comment by nils-soderman** [comment]
With the 1.2.0 release you can now set the setting 
```json
{
    "batch-runner.saveFileBeforeRun": true
}
```
to automatically save the batch files before running them.

Full changelog here: https://github.com/nils-soderman/vscode-batch-runner/releases/tag/1.2.0

**Comment by lucasc190** [comment]
Is there a reason you didn't make this the default? As far as I know, that's the behaviour in the vast majority of code editors. I can't personally think of any reason why someone would want an easy way to run the current file without making sure it's saved first. I also just think it's more intuitive for an easy command to run the file the user is looking at to run *the version of it* they're looking at (including any unsaved changes) (i.e. save it first).

**Comment by nils-soderman** [comment]
Hi,

No, no real reason, chose to default it to `false` just because that was the current behavior of the extension.
But you raise some valid points, and I agree that we should default this to `true` instead.

**Comment by nils-soderman** [comment]
With the latest release _([1.3.0](https://github.com/nils-soderman/vscode-batch-runner/releases/tag/1.3.0))_ `batch-runner.saveFileBeforeRun` now defaults to `true`.
Thanks for the suggestion!
