### ISSUE TITLE
unable to find batch

### ISSUE THREAD

**Issue by Premkanna22** [nils-soderman/vscode-batch-runner#15]
not existing

**Comment by nils-soderman** [comment]
Hi, could you please provide more information or perhaps a screenshot of the issue?
Where are you getting this _"unable to find batch"_ message? and what do you click/run to trigger it?

**Comment by nils-soderman** [comment]
Due to a lack of information I'm going to close this issue for now, feel free to re-open it with more information on how to reproduce this.
