### ISSUE TITLE
Batch will not run in terminal.

### ISSUE THREAD

**Issue by 4Cafes** [nils-soderman/vscode-batch-runner#16]
I can not get the batch file to run in the built in terminal it will just open a separate CMD prompt and run it there.

**Comment by nils-soderman** [comment]
Make sure you have the setting `batch-runner.runBatchIn` set to `"Terminal"`.
or are you trying to run the batch file as administrator? If so VS Code must be started with admin privileges to be able to run in the terminal.

Cheers,
Nils

**Comment by nils-soderman** [comment]
Hi,

Going to close this issue now due to a lack of activity.
Feel free to re-open this issue with more information if you're still experiencing this issue.
