### ISSUE TITLE
Some posts are deleted because they don't fit.

### ISSUE THREAD

**Issue by Mcdikmen** [nils-soderman/vscode-batch-runner#20]
Hello,

Some Cmd outputs  are deleted because they don't fit.

![image](https://github.com/user-attachments/assets/3065b0e8-c6cc-43d6-a14d-665d66c83118)
![image](https://github.com/user-attachments/assets/d6291367-8730-4803-a9b6-e896618c482f)
![image](https://github.com/user-attachments/assets/e063d512-fa47-4aa1-bc05-938a34f46746)

**Comment by nils-soderman** [comment]
Hi,
This extension only provides a shortcut for running batch files in the terminal, the terminal itself is provided by VS Code.
Please post this on: https://github.com/microsoft/vscode/issues
