### ISSUE TITLE
Support running scripts as admin

### ISSUE THREAD

**Issue by GarrettCarter-eaton** [nils-soderman/vscode-batch-runner#4]
My workflow involves running batch scripts as admin.

Perhaps you could add this as a global toggle "Run all scripts as admin"
or... Add an additional right click option "Run this script as admin"

**Comment by nils-soderman** [comment]
Hi,

I've now published [v0.0.7](https://marketplace.visualstudio.com/items/NilsSoderman.batch-runner/changelog) where I added the command `batch-utils.execBatchFileAsAdmin`.

There are several way to execute a batch file as admin, will probably document this in the ReadMe later on:
1. If you hold down <kbd>Alt</kbd> while right clicking a file in the explorer, you'll get the option to run it as admin
2. There's now a dropdown next to the run icon where you can set it to run as admin:
![image](https://user-images.githubusercontent.com/20663273/184543264-69dacb59-617f-461d-bedf-4e6a18668a26.png)

or you could always map the command to a hotkey / just run the command from <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd>.


Thank you for the idea/feedback and let me know if you run into any issues using it!


Cheers,
Nils
