### ISSUE TITLE
Doesn't work if default terminal is changed

### ISSUE THREAD

**Issue by ezillinger** [nils-soderman/vscode-batch-runner#5]
First off, thanks for making this plugin!

I've changed my default terminal to git bash (instead of cmd.exe) and the plugin now tries to run .cmd scripts in bash. It should explicitly open a cmd.exe terminal rather than relying on the default.

**Comment by nils-soderman** [comment]
Hi,

This should now be fixed in [v0.0.8](https://marketplace.visualstudio.com/items/NilsSoderman.batch-runner/changelog), thank you for reporting this issue!

Cheers,
Nils
