### ISSUE TITLE
Strange behavior each line is run separately

### ISSUE THREAD

**Issue by Kotsuha** [nils-soderman/vscode-batch-runner#7]
```
echo Hello
set foo=bar
echo 1
echo 2
echo 3
echo %bar%
```

What I see in VSCode terminal

```
C:\Temp>echo Hello
Hello

C:\Temp>set foo=bar

C:\Temp>echo 1
1

C:\Temp>echo 2
2

C:\Temp>echo 3
3

C:\Temp>echo
ECHO is on.

C:\Temp>
```

Batch Runner v1.0.0
VSCode 1.72.2

**Comment by nils-soderman** [comment]
Hi,

Yes, wouldn't that be the expected result? This is the same as running the batch file in cmd/powershell _(This extension executes your batch file in cmd.exe by default)_.

Maybe you wanted to insert `@echo off` at the top of the batch files, to prevent the commands from being shown?
Also, you probably wanted to echo `%foo%`, not `%bar%`:

```batch
@echo off

echo Hello
set foo=bar
echo 1
echo 2
echo 3
echo %foo%
```

```
Hello
1
2
3
bar

C:\Temp>
```

Cheers,
Nils

**Comment by Kotsuha** [comment]
Oops, it's a silly mistake made by me. Thank you! It's working as expected now.
