### ISSUE TITLE
Send parameters and potentially integrate with launch.json

### ISSUE THREAD

**Issue by ruffin--** [nils-soderman/vscode-batch-runner#8]
How do I send parameters to the command being executed?

If there's not a way I've missed (AIA in I have), something like the [`args` property of `launch.json` in node](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration) would be really useful.

> These attributes are only available for launch configurations of request type `launch`:
> 
> ...
>   
> `args` - arguments passed to the program to debug. This attribute is of type array and expects individual arguments as array elements.

**Comment by nils-soderman** [comment]
Hi,

As of right now there's no way to pass along arguments.

Been thinking about adding another command e.g. "Run batch file with arguments" that will spawn a text input dialog first to allow the user to insert any number of arguments:
![image](https://user-images.githubusercontent.com/20663273/221411546-77d180d1-57d5-4585-8743-6fe024727d95.png)

Will be looking into this in the near future!

**Comment by nils-soderman** [comment]
H,

Just released version [1.1.0](https://github.com/nils-soderman/vscode-batch-runner/releases/tag/1.1.0) which includes a new command `batch-utils.execBatchFileArgs` that spawns an input dialog where you can type the arguments.

Cheers,
Nils
